# Generated by Django 4.2 on 2025-05-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_models', '0002_modeltag_remove_model_project_id_model_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('config', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('log_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_session', to='ml_models.modelversion')),
            ],
            options={
                'verbose_name_plural': 'Training Sessions',
                'db_table': 'training_session',
            },
        ),
    ]
