# Generated by Django 4.2 on 2025-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
