# Generated by Django 4.2 on 2025-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_trainingsession_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='logs',
            field=models.TextField(blank=True, help_text='Short log summary or status messages', null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='log_path',
            field=models.CharField(blank=True, help_text='Path to the full training log file', max_length=1024, null=True),
        ),
    ]
