# Generated by Django 4.2 on 2025-01-30 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ml_models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Model Frameworks',
                'db_table': 'model_framework',
            },
        ),
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Model Tasks',
                'db_table': 'model_task',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ml_models.modelframework')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ml_models.modeltask')),
            ],
            options={
                'verbose_name_plural': 'ML Models',
                'db_table': 'ml_model',
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('checkpoint', models.FileField(blank=True, max_length=1024, null=True, upload_to=ml_models.models.get_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pt', 'pth', 'h5', 'onnx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='ml_models.model')),
            ],
            options={
                'verbose_name_plural': 'Model Versions',
                'db_table': 'model_verison',
                'unique_together': {('model', 'version')},
            },
        ),
    ]
