# Generated by Django 4.2 on 2025-05-17 10:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ml_models.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('datasets', '0001_initial'),
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Model Tags',
                'db_table': 'model_tag',
            },
        ),
        migrations.RemoveField(
            model_name='model',
            name='project_id',
        ),
        migrations.AddField(
            model_name='model',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelversion',
            name='config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='dataset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to='datasets.dataset'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='logs',
            field=models.FileField(blank=True, null=True, upload_to=ml_models.models.get_model_artifact_path),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('training', 'Training'), ('trained', 'Trained'), ('failed', 'Failed'), ('deployed', 'Deployed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='checkpoint',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=ml_models.models.get_model_artifact_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pt', 'pth', 'h5', 'onnx'])]),
        ),
        migrations.AddField(
            model_name='model',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='models', to='ml_models.modeltag'),
        ),
    ]
