# Generated by Django 4.2 on 2025-05-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_modeltag_remove_model_project_id_model_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='model_version_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
