# Generated by Django 4.2 on 2025-06-03 18:42

from django.db import migrations, models
import ml_models.models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0003_modelversion_model_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='logs',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=ml_models.models.get_model_artifact_path),
        ),
    ]
