# Generated by Django 4.2 on 2025-01-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('task', models.CharField(choices=[('classification', 'Classification'), ('detection', 'Object Detection'), ('segmentation', 'Segmentation'), ('custom', 'Custom')], max_length=50)),
                ('framework', models.CharField(choices=[('tensorflow', 'TensorFlow'), ('pytorch', 'PyTorch'), ('onnx', 'ONNX'), ('custom', 'Custom')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'ML Models',
                'db_table': 'ml_model',
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('checkpoint_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='models.model')),
            ],
            options={
                'verbose_name_plural': 'Model Versions',
                'db_table': 'model_verison',
            },
        ),
    ]
