# Generated by Django 4.2 on 2025-01-26 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_modelframwork_modeltask_alter_model_framework_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Model Frameworks',
                'db_table': 'model_framework',
            },
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('model', 'version')},
        ),
        migrations.AlterField(
            model_name='model',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='models.modelframework'),
        ),
        migrations.DeleteModel(
            name='ModelFramwork',
        ),
    ]
