# Generated by Django 4.2 on 2025-01-26 10:51

import django.core.validators
from django.db import migrations, models
import models.models as ml_model


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_modelframework_alter_modelversion_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelversion',
            name='checkpoint_path',
        ),
        migrations.AddField(
            model_name='modelversion',
            name='checkpoint',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=ml_model.get_model_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pt', 'pth', 'h5', 'onnx'])]),
        ),
    ]
